apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    demo: the-deploy-master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    demo: the-deploy-master
